### ISSUE TITLE
Hot Module Replacement / "There is already a template with the ID"

### ISSUE THREAD

**Issue by chrishale** [megahertz/twigjs-loader#2]
I've been using this loader with storybook/html to develop a component library, that can be dropped into a Drupal install.

I'm not sure if this is an issue with twigjs or this loader, but I did have some issues using this with webpack's hot reloading that is pre-configured in Storybook.

Whenever webpack tried to reload a twig file (using the loader), I'd get an error stating "There is already a template with the ID".

With the `renderTemplate` option, I was able to work around this issue by clearing the twig cache:

```
use: {
      loader: "twigjs-loader",
      options: {
        renderTemplate(twigData, dependencies) {
          return `
            ${dependencies}
            var Twig = require("twig");
            Twig.cache();
            var tpl = Twig.twig(${JSON.stringify(twigData)});
            module.exports = function(context) { return tpl.render(context); };
            module.exports.id = ${JSON.stringify(twigData.id)};
            module.exports.default = module.exports;
          `;
        }
      }
    },
```

I'm not sure this is something that's worth building into the loader as a configurable option as it's probably a niche use case, so feel free to close this issue.

But I figured even a closed issue in a repo with a workaround, might help someone in the future who is working with a similar setup.

**Comment by megahertz** [comment]
Thank you for the report. I'll try to investigate it in a few days. So, this problem appears only with HMR, not on normal build?

**Comment by chrishale** [comment]
That's correct, I believe it's the webpack dev server that Storybook uses. It would load/compile the twig template fine the first time, but if I saved a change to the file - I'd see an error. Presumably because the ID  / filepath was still in the cache.

**Comment by megahertz** [comment]
It seems that with a basic configurations HMR works fine, like in [the example](https://github.com/megahertz/twigjs-loader/tree/master/examples/frontend). Do you have any idea which webpack settings can lead to such a problem?

**Comment by megahertz** [comment]
Thank you for the information. I've included this fix into the default renderTemplate function.
