### ISSUE TITLE
Dynamic Inheritance with `extends`

### ISSUE THREAD

**Issue by wfpfork** [megahertz/twigjs-loader#7]
Hey there 👋

Thanks in advance for this awesome piece of software!

We use _twigjs-loader_ with _Storybook_ and it works quite well, however this morning we came across an issue, that might be related to _twigjs_ not being 100% compatible with the actual _Twig_.

Works:

```
{# page.twig #}
{% extends '@components/foo/bar.twig' %}
```

Does not work:

1.  Passing `myTemplate` as a parameter (value is '@components/foo/bar.twig'):

    ```
    {# page.twig #}
    {% extends myTemplate %}
    ```

    **Error message** in _Storybook_ looks like this (replaced local paths to _page.twig_ and _node_modules_ with `...`):
    
    ```
    Module build failed (from ./node_modules/twigjs-loader/index.js):
    Error: Can't resolve 'myTemplate' in '/Users/.../page'
        at doResolve (/Users/.../node_modules/enhanced-resolve/lib/Resolver.js:209:21)
        at hook.callAsync (/Users/.../node_modules/enhanced-resolve/lib/Resolver.js:285:5)
        at _fn0 (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), 
    ```

1. Defining `myTemplate` before `extends`:

    ```
    {# page.twig #}
    {% set myTemplate = '@components/foo/bar.twig' %}
    {% extends myTemplate %}
    ```

    I know it's not allowed but we tried anyways 🙃 (@see https://github.com/twigjs/twig.js/issues/391)

    Error message: `Error: Can't resolve 'myTemplate'`

1. Using `default`

    ```
    {# page.twig #}
    {% extends myTemplate|default('@components/foo/bar.twig') %}
    ```

    Error message: `Error: Can't resolve 'default'`

1. Using `is defined`

    ```
    {# page.twig #}
    {% extends myTemplate is defined ? myTemplate : '@components/foo/bar.twig' %}
    ```

    Error message: `TypeError: Cannot read property 'indexOf' of undefined`

1. Using `is defined` with `default`

    ```
    {# page.twig #}
    {% extends myTemplate|default is defined ? myTemplate : '@components/foo/bar.twig' %}
    ```

    Error message: `TypeError: Cannot read property 'indexOf' of undefined`

The Twig documentation however states, that dynamic inheritance within `extends` should be possible: https://twig.symfony.com/doc/3.x/tags/extends.html#dynamic-inheritance

Thank you very much for looking into this 👏

**Comment by megahertz** [comment]
Hi. Unfortunately, I have no plans to support dynamic imports. Internally, the library uses resolver of webpack, which only works with static paths.
