### ISSUE TITLE
create_attribute() causing error

### ISSUE THREAD

**Issue by joshwaaaah** [megahertz/twigjs-loader#9]
Hey,

Great work on the loader. I'm currently using it with Storybook, and in one of my Twig templates I'm wanting to create a new attribute, but it's throwing the error `create_attribute function does not exist and is not defined in the context`... 

Do you happen to have any ideas why?

I'm using version 1.0.2 if that helps at all. Any help would be much appreciated!

**Comment by megahertz** [comment]
Hi. It's not related to the loader. Try to ask about it [here](https://github.com/kalamuna/twig-drupal-filters/issues/43)
